---
- name: Get user info for the iac_user
  ansible.builtin.getent:
    database: passwd
    key: "{{ iac_user }}"
  when:
    - "iac_user is not none"

- name: Set the config file root
  set_fact:
    _iac_root_path: >-
      {%- if iac_user is not none -%}
      {{ ansible_facts.getent_passwd[iac_user][4] }}/
      {%- else -%}
      ""
      {%- endif -%}

- name: >-
    Do a small amout of sanity checking - we can't have a null
    iac_user and relative config paths
  fail:
    msg: "At least one config path is relative and no `iac_user` is set!"
  when:
    - >-
      (iac_config_files | selectattr('dest', 'defined')
        | selectattr('dest', 'match', '^[^/]') 
        | list
        | length
      ) > 0
    - "iac_user is none"

- name: Get the controller host for convenience
  set_fact:
    _iac_ansible_controller_hostname: "{{ lookup('pipe', 'hostname') }}"
