---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-iac"
      include_role:
        name: "ansible-role-iac"
      vars:
        iac_user: dan
        iac_group: dan
        iac_no_log: false
        iac_packages:
          - polybar
        iac_directories:
          - path: .config/polybar
            mode: "0700"
        iac_config_files:
          - dest: .config/polybar/config
            src: iac.ini.j2
            vars:
              colors:
                background: "#222"
                background-alt: "#444"
                foreground: "#dfdfdf"
                foreground-alt: "#555"
                primary: "#ffb52a"
                secondary: "#e60053"
                alert: "#bd2c40"

              "bar/i3bar":
                monitor: "${env:MONITOR:eDP-1}"
                monitor-exact: true
                width: 100%
                height: 27
                offset-x: 1%
                offset-y: 1%
                radius: 6.0
                fixed-center: false

                background: ${colors.background}
                foreground: ${colors.foreground}

                line-size: 3
                line-color: #f00

                border-size: 4
                border-color: #00000000

                padding-left: 0
                padding-right: 2

                module-margin-left: 1
                module-margin-right: 2

                font-0: 'fixed:pixelsize=18;1'
                font-1: 'unifont:fontformat=truetype:size=14:antialias=false;0'
                font-2: 'siji:pixelsize=18;1'

                modules-left: 'i3 active-task next-task'
                modules-center: 'mpd'
                modules-right: 'filesystem alsa pulseaudio xkeyboard memory cpu wlan battery temperature date powermenu'

                tray-position: right
                tray-padding: 2

                wm-restack: i3

                cursor-click: pointer
                cursor-scroll: ns-resize
